export enum MoviesGetterTypes {
  MOVIES_LOADING = "MOVIES_LOADING",
  MOVIES_LOADED = "MOVIES_LOADED",
  MOVIES_LOAD_REJECTED = "MOVIES_LOAD_REJECTED",
  SINGLE_MOVIE_LOADING = "SINGLE_MOVIE_LOADING",
  SINGLE_MOVIE_LOADED = "SINGLE_MOVIE_LOADED",
  SINGLE_MOVIE_LOAD_REJECTED = "SINGLE_MOVIE_LOAD_REJECTED"
}
