export enum MoviesMutationTypes {
  MOVIES_PENDING = "MOVIES_PENDING",
  MOVIES_FULFILLED = "MOVIES_FULFILLED",
  MOVIES_REJECTED = "MOVIES_REJECTED",
  SINGLE_MOVIE_FULFILLED = "SINGLE_MOVIE_FULFILLED",
  SINGLE_MOVIE_REJECTED = "SINGLE_MOVIE_REJECTED"
}
